version: "3.9"

services:
  dimspec:
    build: .
    container_name: dimspec
    ports:
      - "3838:3838"         # Main Shiny app
      - "7000:7000"         # msMatch Shiny app
      - "7001:7001"         # table_explorer Shiny app
      - "7002:7002"         # dimspec-qc Shiny app
      - "8000:8000"         # Plumber API
    volumes:
      - ./data:/opt/DIMSpec/db
      - ./env_glob.txt:/opt/DIMSpec/config/env_glob.txt:ro
      - ./shiny_logs/msmatch:/var/log/shiny/msmatch
      - ./shiny_logs/table_explorer:/var/log/shiny/table_explorer
      - ./shiny_logs/dimspec_qc:/var/log/shiny/dimspec_qc
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
